services:
  postgres:
    image: postgres:15
    container_name: postgres_dev_redacao
    restart: always
    environment:
      POSTGRES_DB: redacao-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dumps:/dumps
    networks:
      - postgres_network

  # Opcional: PgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge